version: '3.9'

services:
  nginx:
    image: nginx:1.31.4@sha256:b34848eff6db786b6b1282d3a9c3fd0b5563dfb6d261df4923378b419e0d24f0
    hostname: nginx
    container_name: tyan0proxy__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
    hostname: cloudflared
    container_name: tyan0proxy__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - tyan0proxy__cloudflared

networks:
  default:
    name: tyan0proxy__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
