version: '3.9'

services:
  nginx:
    image: nginx:1.31.3@sha256:5a88c9c45479443d7be2eadc894b4ed0a9801bae03d97a5760ae13b5c2005942
    hostname: nginx
    container_name: tyan0proxy__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.7.3@sha256:e39ee8da81ad5e05d77f38d2f51c60ca51bf2a8450ac3abab50c17fdb91d91bf
    hostname: cloudflared
    container_name: tyan0proxy__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - tyan0proxy__cloudflared

networks:
  default:
    name: tyan0proxy__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
