version: '3.9'

services:
  nginx:
    image: nginx:1.31.1@sha256:5aca99593157f4ae539a5dec1092a0ad8762f8e2eb1789085a13a0f5622369f6
    hostname: nginx
    container_name: tyan0proxy__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.5.0@sha256:59bab8d3aceec09bf6bdb07d6beca0225ca5cd7ab79436a87ea97978fe1dc4f9
    hostname: cloudflared
    container_name: tyan0proxy__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - tyan0proxy__cloudflared

networks:
  default:
    name: tyan0proxy__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
