name: lint actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  lint-actionlint:
    runs-on: ubuntu-24.04

    steps:
       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

       - uses: reviewdog/action-actionlint@v1.73.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
