name: lint actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  lint-actionlint:
    runs-on: ubuntu-26.04

    steps:
       - uses: actions/checkout@v7.0.1

       - uses: reviewdog/action-actionlint@v1.77.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
